project:
  type: website

website:
  title: 
    "Jillian W. Reynolds"
  navbar:
    left:
      - text: "Jillian W. Reynolds"
        href: index.qmd
      - text: "Research"
        href: research-interests.qmd
      - text: "Papers"
        href: papers.qmd
      - text: "Experiences"
        href: experiences.qmd
      - text: "Skills"
        href: skills.qmd
    search: false

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



